[package]
name = "miner"
version = "0.1.0"
edition = "2024"

[dependencies]
btclib = { version = "0.1.0", path = "../lib" }
anyhow = "1.0"
clap = { version = "4.5.8", features = ["derive"] }
flume = "0.12.0"
tokio = { version = "1.37.0", features = ["full"] }